/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'domix' at '12/5/16 9:39 AM' with Gradle 3.2.1
 *
 * @author domix, @date 12/5/16 9:39 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
