apiVersion: v1
kind: Service
metadata:
  name: ${name}
  labels:
    name: ${name}
spec:
  type: NodePort
  ports:
  - port: ${appPort}
    targetPort: ${appPort}
    nodePort: ${exposedAppPort}
    protocol: TCP
  - port: ${adminPort}
    targetPort: ${adminPort}
    nodePort: ${exposedAdminPort}
    protocol: TCP
  selector:
    name: ${name}